#version: "3.8" # версия вашего docker-compose
services:
  # имеджи, которые запустятся по вашему желанию
  db:
    # название моего имеджа
    image: postgres:12 # скачает image postgres 12 версии
    volumes:
      # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports:
      # порты
      - "5432:5432"
    environment:
      # переменные окружения, меняйте их если хотите поменять пароль, логин или название стартовой базы данных
      POSTGRES_USER: lexa
      POSTGRES_DB: RIP
      POSTGRES_PASSWORD: qwerty123
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000" #порт для API MinIO.
      - "9001:9001" #порт для консоли управления MinIO.
    environment:
      MINIO_ACCESS_KEY: lexa
      MINIO_SECRET_KEY: qwerty123
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerty123
    volumes:
      - redis-data:/data

volumes:
  # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local